spring:
  application:
    name: java-platform
  config:
    import:
      - optional:file:../.env[.properties]
      - optional:file:.env[.properties]
  profiles:
    default: dev

server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
