spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: true
  datasource:
    url: ${ACE_DB_URL}
    username: ${ACE_DB_USERNAME}
    password: ${ACE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
